module.exports = [
    {fa: 'تهران', en: 'Tehran'},
    {fa: 'مشهد', en: 'Mashhad'},
    {fa: 'اصفحان', en: 'Isfahan'},
    {fa: 'کرج', en: 'Karaj'},
    {fa: 'شیراز', en: 'Shiraz'},
    {fa: 'تبریز', en: 'Tabriz'},
    {fa: 'قم', en: 'Qom'},
    {fa: 'اهواز', en: 'Ahvaz'},
    {fa: 'کرمانشاه', en: 'Kermanshah'},
    {fa: 'ارومیه', en: 'Urmia'},
    {fa: 'رشت', en: 'Rasht'},
    {fa: 'زاهدان', en: 'Zahedan'},
    {fa: 'همدان', en: 'Hamadan'},
    {fa: 'کرمان', en: 'Kerman'},
    {fa: 'یزد', en: 'Yazd'},
    {fa: 'اردبیل', en: 'Ardabil'},
    {fa: 'بندرعباس', en: 'Bandar Abbas'},
    {fa: 'اراک', en: 'Arak'},
    {fa: 'اسلامشهر', en: 'Eslamshahr'},
    {fa: 'قزوین', en: 'Qazvin'},
    {fa: 'زنجان', en: 'Zanjan'},
    {fa: 'خرمشهر', en: 'Khorramabad'},
    {fa: 'سنندج', en: 'Sanandaj'},
    {fa: 'ملارد', en: 'Malard'},
    {fa: 'قدس', en: 'Qods'},
    {fa: 'کاشان', en: 'Kashan'},
    {fa: 'گرگان', en: 'Gorgan'},
    {fa: 'گلستان', en: 'Golestan'},
    {fa: 'ساری', en: 'Sari'},
    {fa: 'شهریار', en: 'Shahriar'},
    {fa: 'دذفول', en: 'Dezful'},
    {fa: 'خمینی شهر', en: 'Khomeyni Shahr'},
    {fa: 'بروجرد', en: 'Borujerd'},
    {fa: 'نیشابور', en: 'Nishapur'},
    {fa: 'سبزوار', en: 'Sabzevar'},
    {fa: 'نجف آباد', en: 'Najafabad'},
    {fa: 'آمل', en: 'Amol'},
    {fa: 'بابل', en: 'Babol'},
    {fa: 'ورامین', en: 'Varamin'},
    {fa: 'آبادان', en: 'Abadan'},
    {fa: 'پاکدشت', en: 'Pakdasht'},
    {fa: 'خوی', en: 'Khoy'},
    {fa: 'ساوه', en: 'Saveh'},
    {fa: 'بجنورد', en: 'Bojnord'},
    {fa: 'قائم شهر', en: 'Qaem Shahr'},
    {fa: 'بوشهر', en: 'Bushehr'},
    {fa: 'قرچاک', en: 'Qarchak'},
    {fa: 'سیرجان', en: 'Sirjan'},
    {fa: 'بیرجند', en: 'Birjand'},
    {fa: 'ایلام', en: 'Ilam'},
    {fa: 'بوکان', en: 'Bukan'},
    {fa: 'مراغه', en: 'Maragheh'},
    {fa: 'ملایر', en: 'Malayer'},
    {fa: 'شهر کرد', en: 'Shahr-e Kord'},
    {fa: 'بندر ماه شهر', en: 'Bandar-e Mahshahr'},
    {fa: 'سمنان', en: 'Semnan'},
    {fa: 'رفسنجان', en: 'Rafsanjan'},
    {fa: 'مه آباد', en: 'Mahabad'},
    {fa: 'گنبد کاووس', en: 'Gonbad-e Kavus'},
    {fa: 'شاهین شهر', en: 'Shahin Shahr'},
    {fa: 'شاهرود', en: 'Shahrud'},
    {fa: 'سقز', en: 'Saqqez'},
    {fa: 'مرودشت', en: 'Marvdasht'},
    {fa: 'زابل', en: 'Zabol'},
    {fa: 'تربت حیدریه', en: 'Torbat-e Heydarieh'},
    {fa: 'خرم شهر', en: 'Khorramshahr'},
    {fa: 'اندیمشک', en: 'Andimeshk'},
    {fa: 'مرند', en: 'Marand'},
    {fa: 'شهرضا', en: 'Shahreza'},
    {fa: 'میان دو آب', en: 'Miandoab'},
    {fa: 'ایزه', en: 'Izeh'},
    {fa: 'بندر انزلی', en: 'Bandar-e Anzali'},
    {fa: 'جهرم', en: 'Jahrom'},
    {fa: 'جیرفت', en: 'Jiroft'},
    {fa: 'مریوان', en: 'Marivan'},
    {fa: 'کمال شهر', en: 'Kamal Shahr'},
    {fa: 'یاسوج', en: 'Yasuj'},
    {fa: 'نظر آباد', en: 'Nazarabad'},
    {fa: 'بهبهان', en: 'Behbahan'},
    {fa: 'بم', en: 'Bam'},
    {fa: 'فسا', en: 'Fasa'},
    {fa: 'قوچان', en: 'Quchan'},
    {fa: 'مسجد سلیمان', en: 'Masjed Soleyman'},
    {fa: 'محمد شهر', en: 'Mohammadshahr'},
    {fa: 'دورود', en: 'Dorud'},
    {fa: 'برازجان', en: 'Borazjan'},
    {fa: 'فردیس', en: 'Fardis'},
    {fa: 'نسیم شهر', en: 'Nasimshahr'},
    {fa: 'اندیشه', en: 'Andisheh'},
    {fa: 'ایرانشهر', en: 'Iranshahr'},
    {fa: 'بانه', en: 'Baneh'},
    {fa: 'چابهار', en: 'Chabahar'},
    {fa: 'رباط کریم', en: 'Robat Karim'},
    {fa: 'کاشمر', en: 'Kashmar'},
    {fa: 'شوشتر', en: 'Shushtar'},
    {fa: 'لاهیجان', en: 'Lahijan'},
    {fa: 'اهر', en: 'Ahar'},
    {fa: 'تربت جام', en: 'Torbat-e Jam'},
]