module.exports = [
    {en: 'A Lifetime Relationship (LTR)',
     fa: 'یک رابطه پایدار'},
    {en: 'A Relationship',
     fa: 'یک رابطه معمولی'},
    {en: 'A Mentor/Teacher',
     fa: 'یک مربی/معلم'},
    {en: 'Someone to Play With',
     fa: 'یک همبازی'},
    {en: 'A Princess by Day, Slut by Night',
     fa: 'یک پرنسس در روز و هرزه در شب'},
    {en: 'Friendship',
     fa: 'دوستی'},
    {en: 'A Master',
     fa: 'ارباب'},
    {en: 'A Mistress',
     fa: 'میسترس'},
    {en: 'A Dominant',
     fa: 'یک دام'},
    {en: 'A Submissive',
     fa: 'یک ساب'},
    {en: 'A Slave',
     fa: 'یک برده'},
    {en: 'Make Money',
     fa: 'درآمد'},
    {en: 'Events',
     fa: 'رویداد'},
]